---
title: "粮食产量计算"
output: html_document
---

#本文件计算全年各市及全省粮食产量和增幅

##第一部分，读取所需数据
* 读取分县各季度分品种播种面积数据，不保留小数
```{r, echo=FALSE, warning=FALSE, comment="", results= "asis"}
library(xtable)
library(reshape2)
name12 <- c('小麦', '大麦', '早稻', '单季晚稻', '连作晚稻', '玉米', '其他谷物', '大豆', '蚕豌豆', '杂豆', '蕃薯', '马铃薯' )
name2 <- c('市', '报期')
name4 <- c('市', '名称', '代码', '报期')

choose <- 3300

cityname <- read.csv(file='E:\\gitR\\production\\name.csv', header = TRUE, stringsAsFactors=FALSE)
area <- read.csv(file='E:\\gitR\\production\\area.csv', header = TRUE, stringsAsFactors=FALSE)
area[is.na(area)] <- 0
area[,5:16]  <- round(area[,5:16] , digits=0)
dispdata <- area[area$city %in% choose,c(-1,-3)]
colnames(dispdata) <- c(name2, name12)
print.xtable(xtable(dispdata, digits=0), type="html")
```
* 读取分县各季度分品种单产数据，保留一位小数
```{r, echo=FALSE, warning=FALSE, comment="", results= "asis"}
yield <- read.csv('E:\\gitR\\production\\yield.csv', header = TRUE, stringsAsFactors=FALSE)
yield[is.na(yield)] <- 0
yield[,5:16]  <- round(yield[,5:16] , digits=1)

dispdata <- yield[yield$city %in% choose, c(-1,-3)]
colnames(dispdata) <- c(name2, name12)
print.xtable(xtable(dispdata, digits=1), type="html")
```
* 读取各市各季度核定增幅数据，保留3位小数
```{r, echo=FALSE, warning=FALSE, comment="", results= "asis"}
gross <- read.csv('E:\\gitR\\production\\gross.csv', header = TRUE, stringsAsFactors=FALSE)
gross[is.na(gross)] <- 0

dispdata <- gross[gross$city %in% choose, ]
colnames(dispdata) <- c(name2, "增幅")
print.xtable(xtable(dispdata, digits=3), type="html")
```
* 读取上年各市各季度平均单产数据，保留1位小数
```{r, echo=FALSE, warning=FALSE, comment="", results= "asis"}
yield14 <- read.csv('E:\\gitR\\production\\yield2014.csv', header = TRUE, stringsAsFactors=FALSE)
yield14[is.na(yield14)] <- 0

dispdata <- yield14[yield14$city %in% choose, ]
colnames(dispdata) <- c(name2, "2014年单产")
print.xtable(xtable(dispdata, digits=1), type="html")
```
* 读取各市定案的播种面积数据，不保留小数
```{r, echo=FALSE, warning=FALSE, comment="", results= "asis"}
cityarea <- read.csv('E:\\gitR\\production\\cityarea.csv', header = TRUE, stringsAsFactors=FALSE)
cityarea[is.na(cityarea)] <- 0
cityarea[,3:14]  <- round(cityarea[,3:14] , digits=0)

dispdata <- cityarea[cityarea$city %in% choose, ]
colnames(dispdata) <- c(name2, name12)
print.xtable(xtable(dispdata, digits=0), type="html")
```
##第二部分，计算产量
1. 县级各季度分品种产量等于播种面积乘以单产，结果不保留小数
```{r, echo=FALSE, warning=FALSE, comment="", results= "asis"}
#新建产量数据框
production <- area;
production[,5:16] <- round(area[,5:16]*yield[,5:16], digits=0)
```
2. 播种面积汇总到市
```{r, echo=FALSE, warning=FALSE, comment="", results= "asis"}
city.area <- aggregate(x=area[,5:16], by=list(city=as.factor(area$city), season=as.factor(area$season)), FUN=sum)
```
3. 产量汇总到市
```{r, echo=FALSE, warning=FALSE, comment="", results= "asis"}
city.prod <- aggregate(x=production[,5:16], by=list(city=as.factor(production$city), season=as.factor(production$season)), FUN=sum)
```
4. 市级产量等于省核定市播种面积乘以全市各品种的平均单产，结果不保留小数
```{r, echo=FALSE, warning=FALSE, comment="", results= "asis"}
#新建市级产量数据框，市级
cityprod <- cityarea
cityprod[,3:14] <- round(city.prod[,3:14]/city.area[,3:14]*cityarea[,3:14]/1000, digits=0)
cityprod[is.na(cityprod)] <- 0
```
5. 计算各品种合计
```{r, echo=FALSE, warning=FALSE, comment="", results= "asis"}
#计算各品种合计数
cityprod$V0 <- rowSums(cityprod[,3:14])
cityarea$V0 <- rowSums(cityarea[,3:14])
```

##第三部分，汇总数据
```{r, echo=FALSE, warning=FALSE, comment="", results= "asis"}
x <- aggregate(x=cityarea[,3:15], by=list(city=as.factor(cityarea$city)), FUN=sum)
x$season <- 'Q0'
cityarea <- rbind(cityarea, x)
x <- aggregate(x=cityarea[,3:15], by=list(season=as.factor(cityarea$season)), FUN=sum)
x$city <- 3300
cityarea <- rbind(cityarea, x)

x <- aggregate(x=cityprod[,3:15], by=list(city=as.factor(cityprod$city)), FUN=sum)
x$season <- 'Q0'
cityprod <- rbind(cityprod, x)
x <- aggregate(x=cityprod[,3:15], by=list(season=as.factor(cityprod$season)), FUN=sum)
x$city <- 3300
cityprod <- rbind(cityprod, x)

dispdata <- cityprod[cityprod$city %in% choose,]
print.xtable(xtable(dispdata), type="html")
```


##第四部分，计算增幅
```{r, echo=FALSE, comment="", results= "asis", warning=FALSE, comment="", results= "asis"}

citydata <- merge(x=cityarea[,c('city','season','V0')],y=cityprod[,c('city','season','V0')], by=c('city','season'), suffixes = c(".a",".p"))
citydata <- merge(x=citydata, y=yield14[,c('city','season','V0')], by=c('city','season'), suffixes = c("",".y14"))
citydata <- merge(x=citydata, y=gross[,c('city','season','V0')], by=c('city','season'), suffixes = c("",".ag"))
citydata$V0.pg <- round((citydata$V0.ag+100)*citydata$V0.p/citydata$V0.a/citydata$V0*1000-100, digits=1)
citydata$V0.y <- round(x=citydata$V0.p/citydata$V0.a*1000, digits = 1)
citydata$V0.yg <- round(x=citydata$V0.y/citydata$V0*100-100, digits = 1)
citydata$V0.ag <- round(x=citydata$V0.ag, digits = 1)
```


##2015年粮食监测数据反馈总表
```{r, echo=FALSE, comment="", results= "asis", warning=FALSE, comment="", results= "asis"}
dispdata <- citydata[citydata$city %in% choose,order(colnames(citydata))]
dispdata <- merge(x=dispdata, y=cityname, by.x='season', by.y = 'id')
dispdata <- merge(x=dispdata, y=cityname, by.x='city', by.y = 'id')
dispdata <- cbind(dispdata[,c(10,11)], dispdata[,4:9])

dispdata <- dispdata[order(dispdata$name.y,dispdata$name.x),]
colnames(dispdata) <- c('报期', '单位',  '播种面积', '增幅', '产量', '增幅', '单产', '增幅')
xt <- xtable(dispdata)
digits(xt) <- c(0,0,0,0,1,0,1,1,1)
print.xtable(xt, type="html")
```


##2015年播种面积数据
```{r, echo=FALSE, comment="", results= "asis", warning=FALSE, comment="", results= "asis"}
x <- melt(citydata)
x1 <- x[x$variable %in% c('V0.a', 'V0.ag'),]
d1 <- dcast(x1, city ~ variable+season)
d1 <- d1[d1$city %in% choose,]
colnames(d1) <- c('市', '全年', '春', '夏', '秋', '全年增幅', '春增幅', '夏增幅', '秋增幅')
print.xtable(xtable(d1), type="html")
```


##2015年单产数据
```{r, echo=FALSE, comment="", results= "asis", warning=FALSE, comment="", results= "asis"}
x1 <- x[x$variable %in% c('V0.y', 'V0.yg'),]
d2 <- dcast(x1, city ~ variable+season)
d2 <- d2[d2$city %in% choose,]
colnames(d2) <- c('市', '全年', '春', '夏', '秋', '全年增幅', '春增幅', '夏增幅', '秋增幅')
print.xtable(xtable(d2), type="html")
```


##2015年产量数据
```{r, echo=FALSE, comment="", results= "asis", warning=FALSE, comment="", results= "asis"}
x1 <- x[x$variable %in% c('V0.p', 'V0.pg'),]
d3 <- dcast(x1, city ~ variable+season)
d3 <- d3[d3$city %in% choose,]

colnames(d3) <- c('市', '全年', '春', '夏', '秋', '全年增幅', '春增幅', '夏增幅', '秋增幅')
print.xtable(xtable(d3), type="html")


```