---
title: "2018年G101乡卡答疑"
author: "牛艳嘉 李冠宇"
output: html_notebook
---
更新时间： `r format(Sys.time(), "%Y年 %b %d日 %a %H:%M:%S ")`

# O, 总
### 1，市级开发区下辖的不涉农街道用不用填报乡卡？
> 答：不用。

# 一，基本情况
### 1，城镇建成区面积和绿地面积这两个指标，乡用填吗？
> 答：乡不用，街道和镇都需要填报。

### 2，居委会、村委会个数包括空壳的吗？
> 答：不包括。

### 3，生活污水全部集中处理的村个数，如何理解全部？
> 答：村卡中对应指标选“1，全部集中处理”的个数求和（不包括居委会）；第16指标同此处理。

# 二，人口与就业
### 1，一二三产从业人员按户籍人口填还是常住人口填？
> 答：常住人口。

# 三，农业
### 1，农民专业合作社成员数的计量单位是否应从“户”改成“人”？
> 答：是“户”的。农民专业合作社成员本来就是户，按户填报。

### 2，农业技术服务机构从业人员数按什么原则填报？
> 答：填报农业技术服务机构的登记在册人员数，不能出现某乡镇没有机构但是有技术服务人员的情况。

# 四，财政经济
###  1，一般公共预算收入/支出理解不清楚，希望说明非税收入中的专项收入、行政事业性收费、罚没收入和其他收入。
> 答：一般公共财政预算收入如果取不到数按照往年的公共财政收入/支出理解。

###  2， 规上工业产值等部分指标，因专业原因，暂时没有数据，怎么办。
> 答：填报好其他数据后先暂存，联系县级设置不审后再报送。


# 四，贸易与市场
###  1，有部分菜场集贸市场现在改成生鲜超市经营，有生鲜蔬菜日用品食品等，在乡卡中算“商品交易市场”吗？  
> 答：不算。经营如此多品类，一般已经在50平米以上，应该符合第55指标。

### 2，商品交易市场季节性的算吗？
> 答：实际开业三个月以上的算，但要经有关部门和组织批准成立，有固定经营场所、设施，有经营管理部门和监管人员，若干市场经营者入内，具体参见指标解释。

# 六，科教文卫
###  1，第58指标，有签长期合同的编外教师能否归入专任教师？
> 答：长期的，固定教学的就算，兼职的和临时代课的不算。

###  2，座落在乡镇的县管小学，是否计算为小学数？
> 答：算，按在地原则统计。

###  3，剧场、影剧院个数，包括单一功能的电影院吗？
> 答：不包括。

###  4，乡镇卡中的图书馆、文化站与村卡中相同吗？
> 答：乡镇卡中的图书馆标准更高，仅指图书馆，不包括图书室；因村大部有图书室，所以该指标乡镇卡中数应该小于村卡汇总数。

# 七，社会保障
###  1，各种社会福利收养性单位数指标，私人创办、经过民政部门审批的养老院，确以盈利为目的，是否算？
> 答：算。

###  2，城乡居民养老保险和医疗保险包不包括城镇居民养老保险和医疗保险？
> 答：包括。按国发〔2014〕8号文件精神，城乡居民养老保险为原新型农村社会养老保险（称新农保）和城镇居民社会养老保险（城居保）合并而来；根据国发〔2016〕3号文件精神，城乡居民基本医疗保险（城乡居民医保）为原城镇居民基本医疗保险（城镇居民医保）和新型农村合作医疗（新农合）统一而来。所以，应该包括，但均**不包括城镇职工**保险。

### [国务院关于建立统一的城乡居民基本养老保险制度的意见国发〔2014〕8号](http://www.gov.cn/zwgk/2014-02/26/content_2621907.htm)

### [国务院关于整合城乡居民基本医疗保险制度的意见国发〔2016〕3号](http://www.gov.cn/zhengce/content/2016-01/12/content_10582.htm)

# 八，公用事业
###  1，无人的ATM机能不能算金融机构网点？
> 答：不算。同理，营业厅同时附带ATM的，也只能算1个金融机构网点。

###  2，金融机构网点包括扶贫互助协会吗？加入了扶贫互助协会的人可以贷款还款？
> 答：按照金融机构的概念，扶贫互助协会不算，农村资金互助社可以算，因为农村资金互助是银监会发文的，扶贫互助协会仅在民政部门登记。

###  3，公园及休闲健身广场，如何理解休闲健身广场？与村卡中的“体育健身场所”指标有何区别？
> 答：该指标应包括广场。村卡中的“体育健身场所”侧重功能性，满足体育健身即可；而乡镇卡的“休闲健身广场”标准更高，在物理属性上应能称得上广场。


