#
library(stringr)
library(dplyr)

rank_pattern <-'GENERAL|BRIGADIER GENERAL|LIEUTENANT GENERAL|MAJOR GENERAL'
f.caption <- function(x) x %>% html_nodes("tr.dal_row a.title") %>% html_text() %>% str_trim() 
f.url <- function(x) x %>% html_nodes("a.title") %>% html_attr('href')  %>% str_trim() 
f.img <- function(x) x %>% html_nodes("a.da_news_link img") %>% html_attr('src')  %>% str_trim() 
f.alt <- function(x) x %>% html_nodes("a.da_news_link img") %>% html_attr('alt')  %>% str_trim() 
f.remark <- function(x) x  %>% html_nodes("tr.dal_row span.red") %>% html_text() %>% str_trim() 
f.update <- function(x) x %>% html_nodes("tr.dal_row td.updated") %>% html_text() %>% str_trim() 
#f.intro <- function(x) x %>% html_nodes("a.title") %>% html_text() %>% str_trim() 

roster.nodes <- list()
roster.nodes <- fectch.rosters(roster.nodes, 1)
rosters <- data.frame(caption=sapply(roster.nodes, FUN = f.caption) %>% unlist() , stringsAsFactors = F)
rosters <- mutate(rosters, caption=sapply(roster.nodes, FUN = f.caption) %>% unlist())
rosters <- mutate(rosters, rank= str_extract(caption, rank_pattern))
rosters <- mutate(rosters, name=str_replace(caption, rank_pattern, ''))
rosters <- mutate(rosters, url=sapply(roster.nodes, FUN = f.url) %>% unlist())
rosters <- mutate(rosters, id=str_extract(url, '\\d{6}') )
rosters <- mutate(rosters, img=sapply(roster.nodes, FUN = f.img) %>% unlist())
rosters <- mutate(rosters, alt=sapply(roster.nodes, FUN = f.alt) %>% unlist())
rosters <- mutate(rosters, remark=sapply(roster.nodes, FUN = f.remark) %>% unlist())
rosters <- mutate(rosters, year=str_extract(remark, '\\d{4}') )
#rosters <- mutate(rosters, intro=sapply(roster.nodes, FUN = f.intro) %>% unlist())
rosters <- mutate(rosters, update=sapply(roster.nodes, FUN = f.update) %>% unlist())
rosters <- mutate(rosters, update=as.Date(update, '%m/%d%Y'))

write.csv(rosters, 'roster.csv')
save(rosters, file='roster.RData')
